### ISSUE TITLE
simple_rrt_planner_vanilla.hpp should include simple_rrt_planner.hpp or be removed

### ISSUE THREAD

**Issue by calderpg** [UM-ARM-Lab/arc_utilities#2]
@orthez 
We don't want to duplicate code for the planner, since this means that bugs and changes will have to be made to two similar, but separate files. If a simpler interface to  `simple_rrt_planner.hpp` is desired, then it should be built on top of the existing code - for example, a simpler interface that simply includes `simple_rrt_planner.hpp` and provides wrapper functions, rather than copying the planner directly.

**Comment by orthez** [comment]
Yes i totally agree with you. However, i had to change the goal_reached function, since i wanted to include a variable goal state. So i had to modify also the main PlanMultiPath function to use the changed goal_reached function. 

function<bool(const T&)>& goal_reached_fn 
--->
function<bool(const T&, const T&)>& goal_reached_fn

so i cannot just use it directly as an interface. Not sure what would be the best solution, 

(1) I could add the modified PlanMultiPath to simple_rrt, which would create a lot of overhead, but i would be able to create a simple interface
(2) remove vanilla from repo and fork simple_rrt to an own standalone version
or (3) replace goal_reached_fn  with the function which accepts two states (would probably screw up backward-compatibility)

**Comment by calderpg** [comment]
I actually do something similar to having variable goal states when I use the planner. In my case, the goal_reached_fn is a member function of a class that stores the goal state, but there are other ways to do it. Since the RRT itself only needs to know if a state meets goal conditions, rather than what the goal state is, that's why PlanMultiPath doesn't take a goal state but takes a goal_reached_fn.

It's entirely possible to have a goal_reached_fn that has variable goals, but it can, and I think it is cleaner,  to implement that inside the goal_reached_fn, rather than adding goal states to the planner itself.

The simplest way to use the existing planner in a would be to do something like this:

```
std::function<bool(const T&)> goal_reached_fn = std::bind(GoalReachedFunction, std::placeholders::_1, goal);
```

**Comment by dmcconachie** [comment]
I'm going to go ahead and remove this file from the repo, current arc_utilities does not include the file in the library that gets built, and if we find we need it, we can recover it from the logs.
